/** Hits */
export const HITS_FETCH_SUCCESS = 'HITS/HITS_FETCH_SUCCESS';
export const HITS_SHOW_LOADER = 'HITS/SHOW_LOADER';
export const HITS_HIDE_LOADER = 'HITS/HIDE_LOADER';
export const HITS_SHOW_ALERT = 'HITS/SHOW_ALERT';
export const HITS_HIDE_ALERT = 'HITS/HIDE_ALERT';

/** Categories */
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES/CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_SET_CATEGORY = 'CATEGORIES/CATEGORIES_SET_CATEGORY';
export const CATEGORIES_SHOW_LOADER = 'CATEGORIES/SHOW_LOADER';
export const CATEGORIES_HIDE_LOADER = 'CATEGORIES/HIDE_LOADER';
export const CATEGORIES_SHOW_ALERT = 'CATEGORIES/SHOW_ALERT';
export const CATEGORIES_HIDE_ALERT = 'CATEGORIES/HIDE_ALERT';

/** Products */
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS/PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_HIDE_LOAD_MORE = 'PRODUCTS/PRODUCTS_HIDE_LOAD_MORE';
export const PRODUCTS_SHOW_LOAD_MORE = 'PRODUCTS/PRODUCTS_SHOW_LOAD_MORE';
export const PRODUCTS_SHOW_LOADER = 'PRODUCTS/SHOW_LOADER';
export const PRODUCTS_HIDE_LOADER = 'PRODUCTS/HIDE_LOADER';
export const PRODUCTS_SHOW_ALERT = 'PRODUCTS/SHOW_ALERT';
export const PRODUCTS_HIDE_ALERT = 'PRODUCTS/HIDE_ALERT';

/** Product */
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT/PRODUCT_FETCH_SUCCESS';
export const PRODUCT_QUANTITY = 'PRODUCT/PRODUCT_QUANTITY';
export const PRODUCT_SIZE = 'PRODUCT/PRODUCT_SIZE';
export const PRODUCT_SIZE_DELETED = 'PRODUCT/PRODUCT_SIZE_DELETED';
export const PRODUCT_SHOW_LOADER = 'PRODUCT/SHOW_LOADER';
export const PRODUCT_HIDE_LOADER = 'PRODUCT/HIDE_LOADER';
export const PRODUCT_SHOW_ALERT = 'PRODUCT/SHOW_ALERT';
export const PRODUCT_HIDE_ALERT = 'PRODUCT/HIDE_ALERT';

/** Cart */
export const CART_PRODUCTS = 'CART/CART_PRODUCTS';
export const CART_LENGTH = 'CART/CART_LENGTH';
export const CART_SUM = 'CART/CART_SUM';
export const CART_DELETE = 'CART/CART_DELETE';
export const CART_SHOW_LOADER = 'CART/SHOW_LOADER';
export const CART_HIDE_LOADER = 'CART/HIDE_LOADER';
export const CART_SHOW_ALERT = 'CART/SHOW_ALERT';
export const CART_HIDE_ALERT = 'CART/HIDE_ALERT';

/** Search */
export const SEARCH_TEXT_STATUS = 'SEARCH/SEARCH_TEXT_STATUS';
export const SEARCH_FIELD_CHANGE = 'SEARCH/SEARCH_FIELD_CHANGE';